function d = importDatasets(foldername)
%IMPORTFILE Import data from a text file
%  DN = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  DN = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  dN = importfile("C:\Users\Geoffrey\Documents\MATLAB\four_features\dset\AmerNoFatigueT1NOV28.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Feb-2020 15:51:41

%% Input handling

% If dataLines is not specified, define defaults
% if nargin < 2
%     dataLines = [10, Inf];
% end

dataLines = [10, Inf];


%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "dN"];
opts.SelectedVariableNames = "dN";
opts.VariableTypes = ["string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dN", "FillValue", 0);

% Import the data

cd(foldername);
files = dir('*.txt');

N = length(files);
d = cell(N,1);

for i = 1:N
    tbl = readtable(files(i).name, opts);
%     tbl.dN;
    d{i} = tbl.dN;
end
cd ..;
%% Convert to output type
% dN = tbl.dN;
end